package com.dhu.gene;

import java.util.Date;

public class RoleAuth extends RoleAuthKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uc_role_auth.createTime
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uc_role_auth.upateTime
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	private Date upateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uc_role_auth.creator
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uc_role_auth.updator
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	private String updator;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uc_role_auth.createTime
	 * @return  the value of t_uc_role_auth.createTime
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uc_role_auth.createTime
	 * @param createTime  the value for t_uc_role_auth.createTime
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uc_role_auth.upateTime
	 * @return  the value of t_uc_role_auth.upateTime
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public Date getUpateTime() {
		return upateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uc_role_auth.upateTime
	 * @param upateTime  the value for t_uc_role_auth.upateTime
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public void setUpateTime(Date upateTime) {
		this.upateTime = upateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uc_role_auth.creator
	 * @return  the value of t_uc_role_auth.creator
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uc_role_auth.creator
	 * @param creator  the value for t_uc_role_auth.creator
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uc_role_auth.updator
	 * @return  the value of t_uc_role_auth.updator
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public String getUpdator() {
		return updator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uc_role_auth.updator
	 * @param updator  the value for t_uc_role_auth.updator
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public void setUpdator(String updator) {
		this.updator = updator;
	}
}