package com.dhu.gene;

public class RoleAuthKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uc_role_auth.authId
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	private Long authId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_uc_role_auth.roleCode
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	private String roleCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uc_role_auth.authId
	 * @return  the value of t_uc_role_auth.authId
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public Long getAuthId() {
		return authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uc_role_auth.authId
	 * @param authId  the value for t_uc_role_auth.authId
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public void setAuthId(Long authId) {
		this.authId = authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_uc_role_auth.roleCode
	 * @return  the value of t_uc_role_auth.roleCode
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public String getRoleCode() {
		return roleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_uc_role_auth.roleCode
	 * @param roleCode  the value for t_uc_role_auth.roleCode
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}
}