package com.dhu.gene;

import com.dhu.gene.RoleAuth;
import com.dhu.gene.RoleAuthExample;
import com.dhu.gene.RoleAuthKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAuthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	long countByExample(RoleAuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int deleteByExample(RoleAuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int deleteByPrimaryKey(RoleAuthKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int insert(RoleAuth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int insertSelective(RoleAuth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	List<RoleAuth> selectByExample(RoleAuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	RoleAuth selectByPrimaryKey(RoleAuthKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int updateByExample(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int updateByPrimaryKeySelective(RoleAuth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_uc_role_auth
	 * @mbg.generated  Fri Sep 16 10:57:36 CST 2016
	 */
	int updateByPrimaryKey(RoleAuth record);
}